### ISSUE TITLE
KYCOnly alternative to LimitableTransferabilityDelegate.

### ISSUE THREAD

**Issue by sirhill** [c-layer/contracts#20]
A simplified compliance delegate using the user registry as a whitelist.

The new delegate will offer an alternative to the existing `LimitableTransferabilityDelegate`. It will inherit `OracleEnrichedDelegate` and check the User Registry a valid for both sender and receiver but will not do any AML checks.

The new token delegate corresponding to `CompliantTokenDelegate` should include the other dependencies as well (Lock, Freeze, Seize, Mintable and RuleEngine). They do not consume much gas cost.

New names should be given to the corresponding `LimitableTransferabilityDelegate` and `CompliantTokenDelegate`. It is proposed to name them `KYCOnlyTransferabilityDelegate` and `KYCOnlyTokenDelegate`

**Comment by bertux** [comment]
work in progress at https://github.com/c-layer/contracts/pull/25
