### ISSUE TITLE
Suggestion to rename this repository into c-layer

### ISSUE THREAD

**Issue by StEvUgnIn** [c-layer/contracts#33]
Hi everyone,

Let's turn [c-layer/contracts](https://github.com/c-layer/contracts) into [c-layer/c-layer](https://github.com/c-layer/c-layer) to endorse it officially as the main (and single) repository.

**Comment by sirhill** [comment]
It is true that C-layer is today mostly a set of smart contract bricks allowing governable and compliant assets.
However, there are more to come about it.
In particular, concerning the tooling and the DApps to use it.

Hence, the choice of naming it contracts.

I agree that the repo name should contain the name c-layer in it. When you clone this repository it won't consider the name of the organization and it would just name it 'contracts. This can be confusing.
Hence, it would make sense to name it c-layer-contracts or or c-layer-protocol

What do you think ?

**Comment by StEvUgnIn** [comment]
Agreed! We could therefore create a c-layer repository with gitmodule so that the developer can clone everything at once. What do you think?
