### ISSUE TITLE
Accessing exceptions list of lock rule

### ISSUE THREAD

**Issue by quinoah** [c-layer/contracts#7]
It could be useful if the core `token` function could return the list of exceptions (`lockExceptions address[]`) allowed to bypass the lock rule, as set in `defineLock`, in addition to the start and end of the rule (`lock uint256[2]`).

**Comment by sirhill** [comment]
I've added this feature in the v1.1.0 release of the C-Layer.
It's not gas optimal but it will definitely help for now to manage the locking capabilities for an issuer.

It's already available on the master branch.
